### ISSUE TITLE
service files support

### ISSUE THREAD

**Issue by ouceduxzk** [nicolov/ros-bazel#16]
i was trying to support generation of services header with .srv files, the command is gensrv, how should i integrate into the generate_messages.bzl files? any hints?

**Comment by nicolov** [comment]
It's pretty much the same thing as messages, so you should be able to follow the existing code for that.

**Comment by ouceduxzk** [comment]
yes, you are right, after read into your codes, i can add the support for the srv and generate the right files. thanks for your amzing repo, helped me a lot
