### ISSUE TITLE
Docker compose failure

### ISSUE THREAD

**Issue by andre-nguyen** [nicolov/ros-bazel#3]
When building the docker file I get 
```
E: Package 'oracle-java8-installer' has no installation candidate
ERROR: Service 'bazeler' failed to build: The command '/bin/sh -c apt-get install -y --no-install-recommends         software-properties-common     && apt-add-repository ppa:webupd8team/java --yes     && echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections     && echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list     && curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -     && apt-get update     && apt-get install -y --no-install-recommends         oracle-java8-installer     && apt-get install -y --no-install-recommends         bazel     && bazel --batch version' returned a non-zero code: 100
```

As a side note, this project is 2 years old, @nicolov is this still the method you use internally at Cruise to build ros packages using Bazel?

**Comment by nicolov** [comment]
Sorry, I will try to update to a newer bazel. This was kind-of the initial prototype, and things have evolved a lot from there. If I were to do it all over again, I would probably just check in all the ROS code in my repo and lay it down in a more bazel-friendly way.

**Comment by andre-nguyen** [comment]
I'm not familiar with bazel but I wonder if we can just do a find_package style call to fetch the .so files and headers from folder in /opt/ros/melodic/ ? What do you think?

**Comment by nicolov** [comment]
You can do that, but you would loose many of the advantages of Bazel,
mainly the ability to build everything from source using your own compiler,
etc..

**Comment by nicolov** [comment]
You should be good with https://github.com/nicolov/ros-bazel/pull/5
